# Generated by Django 4.2.7 on 2023-11-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactfm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Indexview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parshapa', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('flaticon-truck', 'Transparent Best Pricing'), ('flaticon-vessel', 'The Real Time Tracking'), ('flaticon-conveyor', 'Security Sysytem Cargo'), ('flaticon-delivery-truck', 'Warehousing Storage')], max_length=50)),
            ],
        ),
    ]
