# Generated by Django 4.2.7 on 2023-11-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contact',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
