# Generated by Django 4.2.7 on 2023-11-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_service_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('contact', models.TextField()),
            ],
        ),
    ]
