# Generated by Django 4.2.7 on 2023-11-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_slick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('flaticon flaticon-boxes', 'Road Fright Services'), ('flaticon  flaticon-warehouse', 'Warehousing Services'), ('flaticon-vessel', 'Consulting Storage')], max_length=50)),
            ],
        ),
    ]
