# Generated by Django 4.2.7 on 2023-11-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indexview',
            new_name='Icon',
        ),
        migrations.DeleteModel(
            name='Slick',
        ),
    ]
