# Generated by Django 4.2.7 on 2023-11-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_indexview_icon_delete_slick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactfm',
            new_name='Indexfm',
        ),
        migrations.RenameModel(
            old_name='Serviceview',
            new_name='Serviceicon',
        ),
    ]
