# Generated by Django 4.2.7 on 2023-11-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
    ]
