# Generated by Django 4.2.7 on 2023-11-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_contact_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indexform',
        ),
    ]
