# Generated by Django 4.2.7 on 2023-11-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_delete_indexform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
