# Generated by Django 4.2.7 on 2023-11-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_delete_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serviceicon',
            new_name='Service',
        ),
    ]
