# Generated by Django 4.2.7 on 2023-11-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_rename_serviceicon_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
