# Generated by Django 4.2.7 on 2023-11-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
