# Generated by Django 4.2.7 on 2023-11-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_delete_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
